FROM maven:3.9-eclipse-temurin-21

WORKDIR /app

# Cache dependencies first
COPY pom.xml .
RUN mvn -q -DskipTests dependency:go-offline

# Source will be mounted by docker-compose (volume .:/app)
CMD ["mvn", "spring-boot:run"]