CREATE SCHEMA IF NOT EXISTS tr;

SET search_path TO tr;

CREATE TABLE users
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(50)                                        NOT NULL,
    last_name  VARCHAR(50)                                        NOT NULL,
    email      TEXT                                               NOT NULL,
    password   VARCHAR(255)                                       NOT NULL,
    role       VARCHAR(50)                                        NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX uq_users_email_ci ON users (lower(email));

CREATE TYPE account_type AS ENUM ('CASH','CARD','BANK');

CREATE TABLE accounts
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT                    NOT NULL references users (id),
    name       TEXT                      NOT NULL,
    type       account_type              NOT NULL,
    currency   CHAR(3)     DEFAULT 'EUR' NOT NULL,
    archived   BOOL        DEFAULT false NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

CREATE INDEX idx_accounts_user_id ON accounts(user_id);

CREATE TABLE categories
(
    id         BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    user_id    BIGINT      NOT NULL REFERENCES users(id),
    parent_id  BIGINT REFERENCES categories(id),
    name       TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 1. Enforce uniqueness for top-level categories (Where parent_id IS NULL)
CREATE UNIQUE INDEX uq_categories_top_level_name
    ON categories(user_id, LOWER(name))
    WHERE parent_id IS NULL;

-- 2. Enforce uniqueness for sub-categories (Where a parent exists)
CREATE UNIQUE INDEX uq_categories_sub_name
    ON categories(user_id, parent_id, LOWER(name))
    WHERE parent_id IS NOT NULL;

-- 3. General performance index for lookups by user
CREATE INDEX idx_categories_user_id
    ON categories(user_id);