CREATE SCHEMA IF NOT EXISTS tr;

SET
    search_path TO tr;

CREATE TABLE roles
(
    id   BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL
);

CREATE TABLE users
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(50)                                        NOT NULL,
    last_name  VARCHAR(50)                                        NOT NULL,
    email      TEXT                                               NOT NULL,
    password   TEXT                                               NOT NULL,
    role_id    BIGINT                                             NOT NULL REFERENCES roles (id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX uq_users_email ON users (lower(email));

CREATE TABLE account_types
(
    id   BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL
);

CREATE TABLE currencies
(
    id   BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(3) NOT NULL,
    CONSTRAINT chk_currency_name_format CHECK (name ~ '^[A-Z]+$')
);

CREATE UNIQUE INDEX uq_currency_name ON currencies (lower(name));

CREATE TABLE accounts
(
    id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id         BIGINT                    NOT NULL references users (id),
    account_type_id BIGINT                    NOT NULL references account_types (id),
    currency_id     BIGINT                    NOT NULL references currencies (id),
    name            TEXT                      NOT NULL,
    archived        BOOL        DEFAULT false NOT NULL,
    created_at      TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at      TIMESTAMPTZ DEFAULT now() NOT NULL

    CONSTRAINT chk_account_name_length CHECK (length(name) >= 3 AND length(name) <= 20)
);

CREATE UNIQUE INDEX uq_accounts_user_name ON accounts (user_id, lower(name));

CREATE INDEX idx_accounts_user_id ON accounts (user_id);
CREATE INDEX inx_accounts_account_type_id ON accounts (account_type_id);
CREATE INDEX inx_accounts_currency_id ON accounts (currency_id);

CREATE TABLE categories
(
    id                 BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    user_id            BIGINT      NOT NULL REFERENCES users (id),
    parent_category_id BIGINT REFERENCES categories (id),
    name               TEXT        NOT NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 1. Enforce uniqueness for top-level categories (Where parent_category_id IS NULL)
CREATE UNIQUE INDEX uq_categories_top_level_name
    ON categories (user_id, LOWER(name)) WHERE parent_category_id IS NULL;

-- 2. Enforce uniqueness for sub-categories (Where a parent exists)
CREATE UNIQUE INDEX uq_categories_sub_name
    ON categories (user_id, parent_category_id, LOWER(name)) WHERE parent_category_id IS NOT NULL;

-- 3. General performance index for lookups by user
CREATE INDEX idx_categories_user_id
    ON categories (user_id);

CREATE TABLE transactions
(
    id          BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    user_id     BIGINT         NOT NULL REFERENCES users (id),
    account_id  BIGINT         NOT NULL REFERENCES accounts (id),
    category_id BIGINT         NOT NULL REFERENCES categories (id),
    currency_id BIGINT         NOT NULL REFERENCES currencies (id),
    amount      NUMERIC(14, 2) NOT NULL,
    description TEXT,
    occurred_at TIMESTAMPTZ    NOT NULL,
    created_at  TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ    NOT NULL DEFAULT now()
);

CREATE INDEX idx_tx_user_occurred
    ON transactions (user_id, occurred_at DESC);

CREATE INDEX idx_tx_account_occurred
    ON transactions (account_id, occurred_at DESC);

CREATE TABLE budgets
(
    id             BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    user_id        BIGINT      NOT NULL REFERENCES users (id),
    category_id    BIGINT      NOT NULL REFERENCES categories (id),
    name           TEXT        NOT NULL,
    month          DATE        NOT NULL,
    planned_amount NUMERIC(14, 2),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_budget_user_month_category
    ON budgets (user_id, month, category_id)